"""
OCR服务常量定义
"""

# 文件验证相关
ALLOWED_FILE_EXTENSIONS = {'.pdf', '.jpg', '.jpeg', '.png', '.tiff', '.tif'}
MAX_FILE_SIZE_MB = 50
MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024

# API相关
DEFAULT_API_BASE_URL = "https://mineru.net/api/v4"
API_VERSION_V4 = "v4"

# 超时配置（秒）
DEFAULT_UPLOAD_TIMEOUT = 60
DEFAULT_POLL_TIMEOUT = 600
DEFAULT_DOWNLOAD_TIMEOUT = 120
DEFAULT_HEALTH_CHECK_TIMEOUT = 10

# 重试配置
DEFAULT_MAX_RETRIES = 3
DEFAULT_RETRY_DELAY = 1.0
DEFAULT_MAX_RETRY_DELAY = 60.0
DEFAULT_BACKOFF_FACTOR = 2.0

# 轮询配置
DEFAULT_INITIAL_POLL_INTERVAL = 10
DEFAULT_MAX_POLL_INTERVAL = 60
DEFAULT_POLL_BACKOFF_FACTOR = 1.5

# 并发配置
MAX_CONCURRENT_UPLOADS = 5

# ZIP处理
ZIP_EXTRACT_PREFIX = "ocr_zip_"
MAX_RESPONSE_PREVIEW_LENGTH = 200

# Mock数据配置
MOCK_CONFIDENCE = 0.95
MOCK_PROCESSING_TIME = 1.5

# 批处理配置
DEFAULT_BATCH_SIZE = 10