version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BUILD_MODE: ${BUILD_MODE:-production}
    ports:
      - "${PORT:-3000}:80"
    environment:
      # Supabase Configuration
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_SUPABASE_SERVICE_KEY=${VITE_SUPABASE_SERVICE_KEY}
      
      # Database Configuration
      - DB_URL=${DB_URL}
      
      # App Configuration
      - VITE_APP_ENV=${VITE_APP_ENV:-production}
      - VITE_APP_NAME=${VITE_APP_NAME:-Invoice Assistant}
      - VITE_APP_VERSION=${VITE_APP_VERSION:-2.0.22}
      
      # API Configuration
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      
      # Feature Flags
      - VITE_ENABLE_ANALYTICS=${VITE_ENABLE_ANALYTICS:-false}
      - VITE_ENABLE_DEBUG=${VITE_ENABLE_DEBUG:-false}
      
    volumes:
      - nginx_cache:/var/cache/nginx
    restart: unless-stopped
    networks:
      - app-network
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  nginx_cache:

networks:
  app-network:
    driver: bridge