services:
  - type: web
    name: invoice-assistant-backend
    runtime: python
    region: singapore  # 选择新加坡区域，离 Supabase 更近
    buildCommand: "./render_build.sh"
    startCommand: "./start_render.sh"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.10"
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        value: "https://sfenhhtvcyslxplvewmt.supabase.co"
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: APP_ENV
        value: "production"
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: "INFO"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        sync: false