services:
  - type: web
    name: invoice-assistant-backend
    runtime: python
    region: singapore  # 选择新加坡区域，离 Supabase 更近
    buildCommand: "./build.sh"
    startCommand: "gunicorn app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 300"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_PORT
        value: "6543"
      - key: DATABASE_NAME
        value: "postgres"
      - key: DATABASE_USER
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: SUPABASE_URL
        value: "https://sfenhhtvcyslxplvewmt.supabase.co"
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: APP_ENV
        value: "production"
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: "INFO"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        sync: false