name: invoice_assistant
description: 发票助手 Flutter iOS 应用
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase 集成
  supabase_flutter: ^2.10.0
  
  # UI 和主题
  flex_color_scheme: ^8.3.0
  cupertino_icons: ^1.0.8
  
  # 路由管理
  go_router: ^16.2.1
  
  # 状态管理
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.1.2
  
  # 依赖注入
  get_it: ^7.6.4
  
  # 网络和连接
  connectivity_plus: ^6.1.5
  
  # 存储
  shared_preferences: ^2.5.3
  
  # 文件选择
  file_picker: ^8.1.6
  
  # 图像选择
  image_picker: ^1.2.0
  
  # HTTP 请求
  http: ^1.5.0
  
  # 加密
  crypto: ^3.0.6
  
  # URL launcher
  url_launcher: ^6.3.1
  
  # 日期处理
  intl: ^0.20.2
  
  # 数据模型
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # 图表
  fl_chart: ^1.1.0
  
  # PDF查看器
  syncfusion_flutter_pdfviewer: ^31.1.17
  sliver_tools: ^0.2.12
  
  # 滑动操作
  flutter_slidable: ^3.1.1
  
  # 文件下载和压缩
  archive: ^3.4.10
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  
  # 分享功能
  share_plus: ^10.1.3
  
  # 打开文件
  open_file: ^3.5.9
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  
  # 代码生成
  freezed: ^2.5.7
  json_serializable: ^6.9.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/theme_presets.json
  
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont.ttf